service: user-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    MYSQL_DB: ${env:MYSQL_DB}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD}
    MYSQL_HOST: ${env:MYSQL_HOST}

functions:
  createUser:
    handler: createUser.handler  # Ensure this points to 'createUser.js'
    events:
      - http:
          path: user
          method: post

  updateUser:
    handler: updateUser.handler  # Ensure this points to 'createUser.js'
    events:
      - http:
          path: user/{id} 
          method: put
  
  getUser:
    handler: getUser.handler  # Ensure this points to 'createUser.js'
    events:
      - http:
          path: user/{id} 
          method: get
    

  deleteUser:
    handler: deleteUser.handler  # Ensure this points to 'deleteUser.js'
    events:
      - http:
          path: user
          method: delete

plugins:
  - serverless-offline
